services:
  postgres:
    image: postgres:latest
    container_name: olist-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: olist
    ports:
      - "5432:5432"